[project]
name = "optimizon-de-test"
version = "0.1.0"
description = "CLI tool for processing sales data CSVs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-cloud-bigquery>=3.35.1",
    "google-cloud-storage>=3.2.0",
]

